# This viminfo file was generated by Vim 8.2.
# You may edit it if you're careful!

# Viminfo version
|1,4

# Value of 'encoding' when this file was written
*encoding=utf-8


# hlsearch on (H) or off (h):
~H
# Command Line History (newest to oldest):
:wv ~/.vim/register.vim
|2,0,1603186069,,"wv ~/.vim/register.vim"
:registers
|2,0,1603186031,,"registers"
:rv ~/.vim/register.vim
|2,0,1603185887,,"rv ~/.vim/register.vim"

# Search String History (newest to oldest):

# Expression History (newest to oldest):

# Input Line History (newest to oldest):
@tr>
|2,3,1603185948,,"tr>"
@td>
|2,3,1603185941,,"td>"
@th>
|2,3,1603184975,,"th>"

# Debug Line History (newest to oldest):

# Registers:
"a	LINE	0
			<table class="table table-bordered table-striped table-hover"><tbody>
				<tr><td data-toggle="modal" data-target="#"></td></tr>
			</tbody></table>
|3,0,10,1,3,0,1603184869,"		<table class=\"table table-bordered table-striped table-hover\"><tbody>","			<tr><td data-toggle=\"modal\" data-target=\"#\"></td></tr>","		</tbody></table>"
"b	LINE	0
			<div class="modal fade" id="" tabindex="-1" aria-hidden="true"><div class="modal-dialog"><div class="modal-content">
				<div class="modal-header"><h5 class="modal-title" data-dismiss="modal"></h5></div>
				<div class="modal-body">
					<table class="table table-bordered table-striped table-hover"><tbody>
						<tr><td></td></tr>
					</tbody></table>
				</div>
			<div class="modal-footer"><button type="button" class="btn btn-success" data-dismiss="modal">Close</button></div>
			</div></div></div>
|3,0,11,1,9,0,1603184880,"		<div class=\"modal fade\" id=\"\" tabindex=\"-1\" aria-hidden=\"true\"><div class=\"modal-dialog\"><div class=\"modal-content\">","			<div class=\"modal-header\"><h5 class=\"modal-title\" data-dismiss=\"modal\"></h5></div>","			<div class=\"modal-body\">","				<table class=\"table table-bordered table-striped table-hover\"><tbody>","					<tr><td></td></tr>","				</tbody></table>","			</div>",>125
|<"		<div class=\"modal-footer\"><button type=\"button\" class=\"btn btn-success\" data-dismiss=\"modal\">Close</button></div>","		</div></div></div>"
"c	CHAR	0
	 data-toggle="modal" data-target="#"
|3,0,12,0,1,0,1603184896," data-toggle=\"modal\" data-target=\"#\""
"e	CHAR	0
	0f"lvf"hdf>lvf<hd
|3,0,14,0,1,0,1603185049,"0f\"lvf\"hdf>lvf<hd"
"r	CHAR	0
	0fd"a€ýa"cp
|3,0,27,0,1,0,1603186022,"0fd\"a€ýa\"cp"
"w	CHAR	0
	0f<vatS<td>vatS<tr>
|3,0,32,0,1,0,1603185951,"0f<vatS<td>vatS<tr>"
""-	CHAR	0
	https://github.com/JimmXinu/FanFicFare
|3,1,36,0,1,0,1603185980,"https://github.com/JimmXinu/FanFicFare"

# File marks:
'0  640  45  ~/.data/meav.github.io/index.html
|4,48,640,45,1603186069,"~/.data/meav.github.io/index.html"
'1  501  38  ~/.data/meav.github.io/index.html
|4,49,501,38,1603185063,"~/.data/meav.github.io/index.html"

# Jumplist (newest first):
-'  640  45  ~/.data/meav.github.io/index.html
|4,39,640,45,1603186069,"~/.data/meav.github.io/index.html"
-'  1  0  ~/.data/meav.github.io/index.html
|4,39,1,0,1603185780,"~/.data/meav.github.io/index.html"
-'  501  38  ~/.data/meav.github.io/index.html
|4,39,501,38,1603185063,"~/.data/meav.github.io/index.html"
-'  1735  10  ~/.data/meav.github.io/index.html
|4,39,1735,10,1603184917,"~/.data/meav.github.io/index.html"

# History of marks within files (newest to oldest):

> ~/.data/meav.github.io/index.html
	*	1603186058	0
	"	640	45
	.	640	10
	+	640	3
	+	501	38
	+	640	10
